### ISSUE TITLE
Google Collab doesnt generate the output file

### ISSUE THREAD

**Issue by gamer-zee** [camenduru/video-retalking-colab#3]
even after finishing all the process, the mp4 file isn't created

**Comment by Broukmiken** [comment]
/content/video-retalking
/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Traceback (most recent call last):
  File "/content/video-retalking/inference.py", line 16, in <module>
    from third_part.GPEN.gpen_face_enhancer import FaceEnhancement
  File "/content/video-retalking/third_part/GPEN/gpen_face_enhancer.py", line 11, in <module>
    from utils.inference_utils import Laplacian_Pyramid_Blending_with_mask
  File "/content/video-retalking/utils/inference_utils.py", line 5, in <module>
    from models import load_network, load_DNet
  File "/content/video-retalking/models/__init__.py", line 2, in <module>
    from models.DNet import DNet
  File "/content/video-retalking/models/DNet.py", line 10, in <module>
    from models.base_blocks import LayerNorm2d, ADAINHourglass, FineEncoder, FineDecoder
  File "/content/video-retalking/models/base_blocks.py", line 9, in <module>
    from basicsr.archs.arch_util import default_init_weights
  File "/usr/local/lib/python3.10/dist-packages/basicsr/__init__.py", line 4, in <module>
    from .data import *
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'
